### ISSUE TITLE
how to use cmd、minion and states

### ISSUE THREAD

**Issue by lvs071103** [madflojo/salt-api-reactor-formula#5]
@madflojo 
how to use cmd minion and states？Do you have a test case? thanks

**Comment by lvs071103** [comment]
```
$ curl -ki https://10.16.1.170:8000/hook/cmd/run -H "Accept: application/x-yaml" -d tgt='*' -d args="hostname" -d secret_key="d41d8cd98f00b204e9800998ecf8427e"
HTTP/1.1 200 OK
Content-Length: 14
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: POST
Access-Control-Allow-Credentials: true
Date: Sat, 10 Sep 2016 13:33:21 GMT
Access-Control-Allow-Origin: *
Content-Type: application/x-yaml
Set-Cookie: session_id=3e5b01b8ad1b532ecaa8040a4278440c191ce700; expires=Sat, 10 Sep 2016 23:33:21 GMT; Path=/

success: true
```

like this? 

but how to get command:hostname return value

I want get hostname value,  Now realize：

```
curl -k https://localhost:8080/ -H "Accept: application/x-yaml"  -H "X-Auth-Token: 40b37e0eb9ccf131c823064d65e24d5814049054" -d client='local' -d tgt='yunwei-dev' -d fun="cmd.run" -d arg='uptime' 
return:
- yunwei-dev: ' 13:34:19 up 34 days,  4:26,  1 user,  load average: 0.00, 0.00, 0.00'
```

**Comment by lvs071103** [comment]
@madflojo 
please help me !

```
$ curl -ki https://10.16.1.170:8000/hook/cmd/script -H "Accept: application/x-yaml" -d tgt='jack_develop' -d args="/root/mkdir.sh" -d secret_key="d41d8cd98f00b204e9800998ecf8427e"
HTTP/1.1 200 OK
Content-Length: 14
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: POST
Access-Control-Allow-Credentials: true
Date: Mon, 12 Sep 2016 14:24:40 GMT
Access-Control-Allow-Origin: *
Content-Type: application/x-yaml
Set-Cookie: session_id=80fef98e2af65b3458d7e9ed7b45e2feb0a45ad7; expires=Tue, 13 Sep 2016 00:24:40 GMT; Path=/

success: true
```

salt-master log report Error:

```
2016-09-12 22:35:08,423 [salt.utils.templates][ERROR   ][2084] Rendering exception occurred: Jinja variable 'dict object' has no attribute 'script'
2016-09-12 22:35:08,423 [salt.utils.reactor][ERROR   ][2084] Failed to render "/srv/salt/reactor/cmd/script.sls": 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 68, in render_reaction
    data=data)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 304, in render_template
    template, self.rend, self.opts['renderer'], **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/template.py", line 95, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/renderers/jinja.py", line 69, in render
    **kws)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 178, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 386, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'script'
```

how to fix it ?

**Comment by lvs071103** [comment]
I solved it.

```
$ curl -ki https://10.16.1.170:8000/hook/cmd/script -H "Accept: application/x-yaml" -d tgt='jack_develop' -d args='/bin/sh' -d script="/root/mkdir.sh" -d secret_key="d41d8cd98f00b204e9800998ecf8427e"
HTTP/1.1 200 OK
Content-Length: 14
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: POST
Access-Control-Allow-Credentials: true
Date: Mon, 12 Sep 2016 15:07:05 GMT
Access-Control-Allow-Origin: *
Content-Type: application/x-yaml
Set-Cookie: session_id=87725c856ba4a20d5398077ac5f94aef6d48bbb9; expires=Tue, 13 Sep 2016 01:07:05 GMT; Path=/

success: true
```
